export const BASE_URL_API_ENDPOINT = import.meta.env.VITE_BASE_URL_API_ENDPOINT
export const CLOUDINARY_CLOUD_NAME = import.meta.env.VITE_CLOUDINARY_CLOUD_NAME
export const CLOUDINARY_UPLOAD_PRESET_NAME = import.meta.env
  .VITE_CLOUDINARY_UPLOAD_PRESET_NAME
